var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

var tv,_fwsdk;if(tv){if(typeof tv!="object")throw new Error("tv already exists and is not a object");}else tv={};if(tv.freewheel){if(typeof tv.freewheel!="object")throw new Error("tv.freewheel already exists and is not a object");}else tv.freewheel={};if(tv.freewheel.SDK){if(typeof tv.freewheel.SDK!="object")throw new Error("tv.freewheel.SDK already exists and is not a object");}else tv.freewheel.SDK={};_fwsdk=tv.freewheel.SDK;_fwsdk.RENDERER_STATE_INIT=1;_fwsdk.RENDERER_STATE_STARTING=2;
_fwsdk.RENDERER_STATE_STARTED=3;_fwsdk.RENDERER_STATE_COMPLETING=4;_fwsdk.RENDERER_STATE_COMPLETED=5;_fwsdk.RENDERER_STATE_FAILED=6;_fwsdk.EVENT_SLOT_IMPRESSION="slotImpression";_fwsdk.EVENT_AD_IMPRESSION="defaultImpression";_fwsdk.EVENT_AD_QUARTILE="quartile";_fwsdk.EVENT_AD_FIRST_QUARTILE="firstQuartile";_fwsdk.EVENT_AD_MIDPOINT="midPoint";_fwsdk.EVENT_AD_THIRD_QUARTILE="thirdQuartile";_fwsdk.EVENT_AD_COMPLETE="complete";_fwsdk.EVENT_AD_CLICK="defaultClick";_fwsdk.EVENT_AD_MUTE="_mute";
_fwsdk.EVENT_AD_UNMUTE="_un-mute";_fwsdk.EVENT_AD_COLLAPSE="_collapse";_fwsdk.EVENT_AD_EXPAND="_expand";_fwsdk.EVENT_AD_PAUSE="_pause";_fwsdk.EVENT_AD_RESUME="_resume";_fwsdk.EVENT_AD_REWIND="_rewind";_fwsdk.EVENT_AD_ACCEPT_INVITATION="_accept-invitation";_fwsdk.EVENT_AD_CLOSE="_close";_fwsdk.EVENT_AD_MINIMIZE="_minimize";_fwsdk.EVENT_ERROR="_e_unknown";_fwsdk.EVENT_RESELLER_NO_AD="resellerNoAd";_fwsdk.INFO_KEY_CUSTOM_ID="customId";_fwsdk.INFO_KEY_MODULE_TYPE="moduleType";
_fwsdk.MODULE_TYPE_RENDERER="renderer";_fwsdk.MODULE_TYPE_TRANSLATOR="translator";_fwsdk.INFO_KEY_ERROR_CODE="errorCode";_fwsdk.INFO_KEY_ERROR_INFO="errorInfo";_fwsdk.INFO_KEY_ERROR_MODULE="errorModule";_fwsdk.ERROR_IO="_e_io";_fwsdk.ERROR_TIMEOUT="_e_timeout";_fwsdk.ERROR_NULL_ASSET="_e_null-asset";_fwsdk.ERROR_ADINSTANCE_UNAVAILABLE="_e_adinst-unavail";_fwsdk.ERROR_UNKNOWN="_e_unknown";_fwsdk.ERROR_MISSING_PARAMETER="_e_missing-param";_fwsdk.ERROR_NO_AD_AVAILABLE="_e_no-ad";
_fwsdk.ERROR_PARSE_ERROR="_e_parse-error";_fwsdk.ERROR_INVALID_VALUE="_e_invalid-value";_fwsdk.ERROR_NO_RENDERER="_e_no-renderer";_fwsdk.INFO_KEY_SHOW_BROWSER="showBrowser";_fwsdk.INFO_KEY_CUSTOM_EVENT_NAME="customEventName";_fwsdk.EVENT_TYPE_CLICK_TRACKING="CLICKTRACKING";_fwsdk.EVENT_TYPE_IMPRESSION="IMPRESSION";_fwsdk.EVENT_TYPE_CLICK="CLICK";_fwsdk.EVENT_TYPE_STANDARD="STANDARD";_fwsdk.EVENT_TYPE_GENERIC="GENERIC";_fwsdk.EVENT_TYPE_ERROR="ERROR";_fwsdk.EVENT_VIDEO_VIEW="videoView";
_fwsdk.SHORT_EVENT_TYPE_IMPRESSION="i";_fwsdk.SHORT_EVENT_TYPE_CLICK="c";_fwsdk.SHORT_EVENT_TYPE_STANDARD="s";_fwsdk.SHORT_EVENT_TYPE_ERROR="e";_fwsdk.INFO_KEY_PARAMETERS="parameters";_fwsdk.URL_PARAMETER_KEY_ET="et";_fwsdk.URL_PARAMETER_KEY_CN="cn";_fwsdk.URL_PARAMETER_KEY_INIT="init";_fwsdk.URL_PARAMETER_KEY_LAST="last";_fwsdk.URL_PARAMETER_KEY_CT="ct";_fwsdk.URL_PARAMETER_KEY_METR="metr";_fwsdk.URL_PARAMETER_KEY_CR="cr";_fwsdk.URL_PARAMETER_KEY_ERROR_INFO="additional";
_fwsdk.URL_PARAMETER_KEY_ERROR_MODULE="renderer";
_fwsdk.Util={trim:function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},isBlank:function(a){return!a||_fwsdk.Util.trim(a)===""},mixin:function(a,b){var c={};for(var d in b)if(typeof c[d]=="undefined"||c[d]!=b[d])a[d]=b[d];return a},copy:function(a){return _fwsdk.Util.mixin({},a)},bind:function(a,b){var c=Array.prototype.slice.call(arguments);c.shift();b=c.shift();return function(){return a.apply(b,c.concat(Array.prototype.slice.call(arguments)))}},getObject:function(a,b,c){a=a.split(".");
b=b||window;for(var d=0,e;b&&(e=a[d]);d++)b=e in b?b[e]:c?(b[e]={}):undefined;return b},buildNode:function(a,b,c){a.innerHTML=b||"";a=a.getElementsByTagName("script");for(b=0;b<a.length;++b)if(a[b].src){var d=scope.getElementsByTagName("head")[0],e=scope.createElement("script");if(a[b].charset)e.charset=a[b].charset;if(a[b].src)e.src=a[b].src;if(a[b].innerHTML)e.innerHTML=a[b].innerHTML;e.onload=e.onreadystatechange=function(){if(!this.readyState||this.readyState=="loaded"||this.readyState=="complete")d.removeChild(s)};
try{d.appendChild(e)}catch(f){_fwsdk.log("load script err: "+f)}}else{e=a[b].innerHTML;if(c)e=e.replace(/var fw_scope = document;/,"var fw_scope = "+c+";");try{eval(e)}catch(h){_fwsdk.log("load script err: "+h)}}},pingURL:function(a){_fwsdk.log("send callback: "+a);if(a){var b=Math.random(),c=document.createElement("iframe");c.name="_fw_cb_"+b;c.id="_fw_cb_"+b;c.width="0";c.height="0";c.scrolling="no";c.frameborder="0";c.style.position="absolute";c.style.bottom="0";c.style.right="0";c.src=a;document.body&&
document.body.appendChild(c)}},pingURLs:function(a){for(var b=0;b<a.length;b++)_fwsdk.Util.pingURL(a[b])},setParameterInURL:function(a,b,c){if(!a||!b||c===null)return null;var d=false,e;a=a.split("?");var f;c=encodeURIComponent(c);if(a[1]){f=a[1].split("&");for(var h=0;h<f.length;++h){e=f[h].split("=");if(e[0]==b){f[h]=e[0]+"="+c;d=true;break}}e=f.join("&");d||(e=b+"="+c+"&"+e)}else e=b+"="+c;return e=a[0]+"?"+e},isiPad:function(){if(navigator.userAgent.toLowerCase().search("ipad")>-1)return true;
return false},systemVersion:function(){var a=navigator.userAgent.toLowerCase(),b=a.search(/os \d_\d/);if(b>-1){var c=a.substr(b+3,1);a=a.substr(b+5,1);return 1*c+0.1*a}else return 0}};_fwsdk.MediaState=function(){};_fwsdk.MediaState.prototype={};_fwsdk.MediaState.prototype.constructor=_fwsdk.MediaState;_fwsdk.Util.mixin(_fwsdk.MediaState.prototype,{play:function(a){_fwsdk.log(this._name+" play("+a+")")},complete:function(a){_fwsdk.log(this._name+" complete("+a+")")}});
_fwsdk.MediaInitState=function(){this._name="MediaInitState"};_fwsdk.MediaInitState.prototype=new _fwsdk.MediaState;_fwsdk.MediaInitState.prototype.constructor=_fwsdk.MediaInitState;_fwsdk.Util.mixin(_fwsdk.MediaInitState.prototype,{play:function(a){_fwsdk.log(this._name+" play("+a+")");a._state=_fwsdk.MediaPlayingState.instance;a.onStartPlaying()}});_fwsdk.MediaInitState.instance=new _fwsdk.MediaInitState;_fwsdk.MediaPlayingState=function(){this._name="MediaPlayingState"};
_fwsdk.MediaPlayingState.prototype=new _fwsdk.MediaState;_fwsdk.MediaPlayingState.prototype.constructor=_fwsdk.MediaPlayingState;_fwsdk.Util.mixin(_fwsdk.MediaPlayingState.prototype,{complete:function(a){_fwsdk.log(this._name+" complete("+a+")");a._state=_fwsdk.MediaEndState.instance;a.onCompletePlaying()}});_fwsdk.MediaPlayingState.instance=new _fwsdk.MediaPlayingState;_fwsdk.MediaReplayingState=function(){this._name="MediaReplayingState"};_fwsdk.MediaReplayingState.prototype=new _fwsdk.MediaState;
_fwsdk.MediaReplayingState.prototype.constructor=_fwsdk.MediaReplayingState;_fwsdk.Util.mixin(_fwsdk.MediaReplayingState.prototype,{complete:function(a){_fwsdk.log(this._name+" complete("+a+")");a._state=_fwsdk.MediaEndState.instance;a.onCompleteReplaying()}});_fwsdk.MediaReplayingState.instance=new _fwsdk.MediaReplayingState;_fwsdk.MediaEndState=function(){this._name="MediaEndState"};_fwsdk.MediaEndState.prototype=new _fwsdk.MediaState;_fwsdk.MediaEndState.prototype.constructor=_fwsdk.MediaEndState;
_fwsdk.Util.mixin(_fwsdk.MediaEndState.prototype,{play:function(a){_fwsdk.log(this._name+" play("+a+")");a._state=_fwsdk.MediaReplayingState.instance;a.onStartReplaying()}});_fwsdk.MediaEndState.instance=new _fwsdk.MediaEndState;_fwsdk.RendererState=function(){};_fwsdk.RendererState.prototype={};_fwsdk.RendererState.prototype.constructor=_fwsdk.RendererState;
_fwsdk.Util.mixin(_fwsdk.RendererState.prototype,{start:function(){},notifyStarted:function(){},stop:function(){},complete:function(){},notifyCompleted:function(){},fail:function(a){a._rendererState=_fwsdk.RendererFailedState.instance;a._adInstance.complete()}});_fwsdk.RendererInitState=function(){};_fwsdk.RendererInitState.prototype=new _fwsdk.RendererState;_fwsdk.RendererInitState.prototype.constructor=_fwsdk.RendererInitState;_fwsdk.RendererInitState.instance=new _fwsdk.RendererInitState;
_fwsdk.Util.mixin(_fwsdk.RendererInitState.prototype,{start:function(a){a._rendererState=_fwsdk.RendererStartingState.instance;a._renderer.start(a)}});_fwsdk.RendererStartingState=function(){};_fwsdk.RendererStartingState.prototype=new _fwsdk.RendererState;_fwsdk.RendererStartingState.prototype.constructor=_fwsdk.RendererStartingState;_fwsdk.RendererStartingState.instance=new _fwsdk.RendererStartingState;
_fwsdk.Util.mixin(_fwsdk.RendererStartingState.prototype,{notifyStarted:function(a){a._rendererState=_fwsdk.RendererStartedState.instance;a._adInstance.play()}});_fwsdk.RendererStartedState=function(){};_fwsdk.RendererStartedState.prototype=new _fwsdk.RendererState;_fwsdk.RendererStartedState.prototype.constructor=_fwsdk.RendererStartedState;_fwsdk.RendererStartedState.instance=new _fwsdk.RendererStartedState;
_fwsdk.Util.mixin(_fwsdk.RendererStartedState.prototype,{complete:function(a){a._rendererState=_fwsdk.RendererCompletingState.instance}});_fwsdk.RendererCompletingState=function(){};_fwsdk.RendererCompletingState.prototype=new _fwsdk.RendererState;_fwsdk.RendererCompletingState.prototype.constructor=_fwsdk.RendererCompletingState;_fwsdk.RendererCompletingState.instance=new _fwsdk.RendererCompletingState;
_fwsdk.Util.mixin(_fwsdk.RendererCompletingState.prototype,{notifyCompleted:function(a){a._rendererState=_fwsdk.RendererCompletedState.instance;a._adInstance.complete()}});_fwsdk.RendererCompletedState=function(){};_fwsdk.RendererCompletedState.prototype=new _fwsdk.RendererState;_fwsdk.RendererCompletedState.prototype.constructor=_fwsdk.RendererCompletedState;_fwsdk.RendererCompletedState.instance=new _fwsdk.RendererCompletedState;_fwsdk.RendererFailedState=function(){};
_fwsdk.RendererFailedState.prototype=new _fwsdk.RendererState;_fwsdk.RendererFailedState.prototype.constructor=_fwsdk.RendererFailedState;_fwsdk.RendererFailedState.instance=new _fwsdk.RendererFailedState;_fwsdk.Hash=function(){this._keys=[];this._dictionary={}};_fwsdk.Hash.prototype={};_fwsdk.Hash.prototype.constructor=_fwsdk.Hash;
_fwsdk.Util.mixin(_fwsdk.Hash.prototype,{setKeyValue:function(a,b,c){if(a){this._dictionary.hasOwnProperty(a)||(c===0?this._keys.unshift(a):this._keys.push(a));this._dictionary[a]=b}},move:function(a){for(var b=0;b<this._keys.length;b++){var c=this._keys[b];if(c==a){this._keys.splice(b,1);this._keys.push(c);return}}},getValue:function(a){return this._dictionary[a]}});_fwsdk.Ad=function(a){this._adManager=a;this._creatives=[]};_fwsdk.Ad.prototype={};_fwsdk.Ad.prototype.constructor=_fwsdk.Ad;
_fwsdk.Util.mixin(_fwsdk.Ad.prototype,{parse:function(a){this._id=a.adId;var b=0;for(a=a.creatives||[];b<a.length;b++){var c=a[b],d=new _fwsdk.Creative(this._adManager);d.parse(c);this._creatives.push(d)}},getCreative:function(a){for(i=0;i<this._creatives.length;i++)if(this._creatives[i]._id==a)return this._creatives[i];return null}});_fwsdk.Creative=function(a){this._adManager=a;this._parameters={};this._creativeRenditions=[]};_fwsdk.Creative.prototype={};_fwsdk.Creative.prototype.constructor=_fwsdk.Creative;
_fwsdk.Util.mixin(_fwsdk.Creative.prototype,{parse:function(a){this._id=a.creativeId;this._baseUnit=a.baseUnit;this._duration=a.duration*1;for(var b=0,c=a.parameters||[];b<c.length;b++){var d=c[b];this._parameters[d.name]=d.value}b=0;for(c=a.creativeRenditions||[];b<c.length;b++){d=c[b];a=new _fwsdk.CreativeRendition(this._adManager);a.parse(d);a.setDuration(this._duration);a._baseUnit=this._baseUnit;this._creativeRenditions.push(a)}},getCreativeRendition:function(a){for(i=0;i<this._creativeRenditions.length;i++)if(this._creativeRenditions[i]._id==
a)return this._creativeRenditions[i];return null}});_fwsdk.CreativeRendition=function(a){this._adManager=a;this._parameters={};this._primaryCreativeRenditionAsset=null;this._otherCreativeRenditionAssets=[]};_fwsdk.CreativeRendition.prototype={};_fwsdk.CreativeRendition.prototype.constructor=_fwsdk.CreativeRendition;
_fwsdk.Util.mixin(_fwsdk.CreativeRendition.prototype,{getContentType:function(){return this._contentType?this._contentType:this._primaryCreativeRenditionAsset&&this._primaryCreativeRenditionAsset._contentType?this._primaryCreativeRenditionAsset._contentType:null},setContentType:function(a){this._contentType=a},getWrapperType:function(){return this._wrapperType},setWrapperType:function(a){this._wrapperType=a},getWrapperUrl:function(){return this._wrapperUrl},setWrapperUrl:function(a){this._wrapperUrl=
a},getBaseUnit:function(){return this._baseUnit},getPreference:function(){return this._preference},getWidth:function(){return this._width},setWidth:function(a){this._width=a},getHeight:function(){return this._height},setHeight:function(a){this.height=a},getDuration:function(){return this._duration},setDuration:function(a){this._duration=a},getParameter:function(a){return this._parameters[a]},setParameter:function(a,b){if(b)this._parameters[a]=b;else delete this._parameters[a]},getPrimaryCreativeRenditionAsset:function(){return this._primaryCreativeRenditionAsset},
getOtherCreativeRenditionAssets:function(){return this._otherCreativeRenditionAssets},addCreativeRenditionAsset:function(){var a=new _fwsdk.CreativeRenditionAsset(this._adManager);if(this._primaryCreativeRenditionAsset)this._otherCreativeRenditionAssets.push(a);else this._primaryCreativeRenditionAsset=a;return a},parse:function(a){this._id=a.creativeRenditionId;this._contentType=a.contentType;this._wrapperUrl=a.wrapperType;this._preference=a.preference;this._width=a.width*1;this._height=a.height*
1;for(var b=0,c=a.parameters||[];b<c.length;b++){var d=c[b];this._parameters[d.name]=d.value}this._primaryCreativeRenditionAsset=new _fwsdk.CreativeRenditionAsset(this._adManager);this._primaryCreativeRenditionAsset.parse(a.asset);b=0;for(c=a.otherAssets||[];b<c.length;b++){d=c[b];a=new _fwsdk.CreativeRenditionAsset(this._adManager);a.parse(d);this._otherCreativeRenditionAssets.push(a)}}});_fwsdk.CreativeRenditionAsset=function(a){this._adManager=a};_fwsdk.CreativeRenditionAsset.prototype={};
_fwsdk.CreativeRenditionAsset.prototype.constructor=_fwsdk.CreativeRenditionAsset;
_fwsdk.Util.mixin(_fwsdk.CreativeRenditionAsset.prototype,{getName:function(){return this._name},setName:function(a){this._name=a},getUrl:function(){return this._url},setUrl:function(a){this._url=a},getContent:function(){return this._content},setContent:function(a){this._content=a},getMimeType:function(){return this._mimeType},setMimeType:function(a){this._mimeType=a},getBytes:function(){return this._bytes},setBytes:function(a){this._bytes=a},parse:function(a){this._id=a.id;this._name=a.name;this._url=
a.url;this._content=a.content;this._contentType=a.contentType;this._mimeType=a.mimeType;this._bytes=a.bytes*1}});_fwsdk.VideoAdRenderer=function(){};
_fwsdk.VideoAdRenderer.prototype={start:function(a){_fwsdk.log("VideoAdRenderer start() at iOS "+_fwsdk.Util.systemVersion()+" device");var b=a.getAdInstance(),c=b.getSlot(),d=c.getBase().getElementsByTagName("video")[0],e=d.style.pixelWidth?d.style.pixelWidth:d.offsetWidth,f=d.style.pixelHeight?d.style.pixelHeight:d.offsetHeight,h=b.getOtherCreativeRenditions();h.unshift(b.getPrimaryCreativeRendition());h=(new _fwsdk.RenditionSelector(1E3,1,1,0.2)).getBestFitRendition(h,e,f);b.setPrimaryCreativeRendition(h);
var k=h?h.getPrimaryCreativeRenditionAsset():null;if(!k||!k.getUrl())a.processEvent({name:_fwsdk.RENDERER_STATE_FAILED,info:{errorModule:"VideoAdRenderer",errorCode:_fwsdk.ERROR_NULL_ASSET}});else{_fwsdk.Util.isiPad()||a.setCapability(_fwsdk.EVENT_AD_CLICK,_fwsdk.CAPABILITY_STATUS_OFF);if(!a.getParameter(_fwsdk.PARAMETER_PLAY_MIDROLL_BY_CURRENT_VIDEO_ELEMENT)&&c.getTimePositionClass()==_fwsdk.TIME_POSITION_CLASS_MIDROLL&&_fwsdk.Util.systemVersion()>=3.2){var m=true,g=document.createElement("video");
g.width=e;g.height=f;g.style.position=d.style.position;g.style.left=d.style.left;g.style.right=d.style.right;g.style.top=d.style.top;g.style.bottom=d.style.bottom;g.style.background="black";g.controls="controls"}else{m=false;g=d}var l=this,j=null,o=function(n){_fwsdk.log("adVideo event "+n.type);a.processEvent({name:_fwsdk.EVENT_AD_CLICK})},v=function(n){_fwsdk.log("adVideo event "+n.type+" adVideo.paused="+g.paused);g.controls=false},w=function(n){_fwsdk.log("adVideo event "+n.type+" adVideo.controls="+
g.controls);g.controls=false},r=function(n){_fwsdk.log("adVideo event "+n.type);g.removeEventListener("timeupdate",r,false);if(j){clearTimeout(j);j=null}a.processEvent({name:_fwsdk.RENDERER_STATE_STARTED})},p=function(n){var q=null;if(n)_fwsdk.log("ad video event "+n.type);else q="timeout";if(j){clearTimeout(j);j=null}g.removeEventListener("touchend",o,false);g.removeEventListener("ended",p,false);g.removeEventListener("error",p,false);g.removeEventListener("pause",v,false);g.removeEventListener("playing",
w,false);g.removeEventListener("timeupdate",r,false);if(g.error)q="error:"+g.error+",code:"+g.error.code;var t=function(){delete g._fw_videoAdPlaying;q?a.processEvent({name:_fwsdk.RENDERER_STATE_FAILED,info:{errorModule:"VideoAdRenderer",errorInfo:q}}):a.processEvent({name:_fwsdk.RENDERER_STATE_COMPLETED})};a.processEvent({name:_fwsdk.RENDERER_STATE_COMPLETING});if(m){g.parentNode.removeChild(g);d.style.display="";t();b==c._adInstances[c._adInstances.length-1]&&d.play()}else{d.src=l._videoSrc;d.controls=
l._videoControls;_fwsdk.log("load main video "+g.src);g.load();if(c.getTimePositionClass()==_fwsdk.TIME_POSITION_CLASS_MIDROLL&&l._videoCurrentTime>0){g.addEventListener("playing",function(){g.removeEventListener("playing",arguments.callee,false);var u=1,x=setInterval(function(){if(g.currentTime<l._videoCurrentTime&&u<10){_fwsdk.log("set currentimte to "+l._videoCurrentTime+" time "+u);u++;try{g.currentTime=l._videoCurrentTime}catch(y){}}else{_fwsdk.log("set currentimte as "+g.currentTime);clearInterval(x);
t()}},500)},false);d.play()}else t()}};if(!m){l._videoSrc=d.src;l._videoCurrentTime=d.currentTime;l._videoControls=d.controls;if(_fwsdk.Util.systemVersion()<4.2)d.controls=false;d._fw_videoAdPlaying=true}e=function(){g.addEventListener("touchend",o,false);g.addEventListener("ended",p,false);g.addEventListener("error",p,false);g.addEventListener("pause",v,false);g.addEventListener("playing",w,false);g.addEventListener("timeupdate",r,false);g.src=k.getUrl();if(m){d.pause();d.style.display="none";d.parentNode.appendChild(g)}_fwsdk.log("play video ad "+
g.src);g.load();if(_fwsdk.Util.systemVersion()<4.2)j=setTimeout(p,3E3);g.play()};if(!_fwsdk.VideoAdRenderer._fw_playedDummyVideo&&!m&&_fwsdk.Util.systemVersion()<4.2){_fwsdk.VideoAdRenderer._fw_playedDummyVideo=true;_fwsdk.log("play dummy video");g.src="";g._fw_videoAdPlaying=true;g.load();g.play();setTimeout(e,500)}else e()}},info:function(){return{moduleType:_fwsdk.MODULE_TYPE_RENDERER}}};_fwsdk.VideoAdRenderer.prototype.constructor=_fwsdk.VideoAdRenderer;
_fwsdk.RendererController=function(a,b){this._adManager=a;this._adInstance=b;this._renderer=null;this._rendererState=_fwsdk.RendererInitState.instance};_fwsdk.RendererController.prototype={};_fwsdk.RendererController.prototype.constructor=_fwsdk.RendererController;
_fwsdk.Util.mixin(_fwsdk.RendererController.prototype,{getAdInstance:function(){return this._adInstance},processEvent:function(a){var b=a.name;if(b==_fwsdk.RENDERER_STATE_STARTED)this._rendererState.notifyStarted(this);else if(b==_fwsdk.RENDERER_STATE_COMPLETING)this._rendererState.complete(this);else if(b==_fwsdk.RENDERER_STATE_COMPLETED)this._rendererState.notifyCompleted(this);else if(b==_fwsdk.RENDERER_STATE_FAILED){this._adInstance.getSlot()._scheduledAdInstance=null;this._adInstance.getEventCallback(_fwsdk.EVENT_ERROR,
_fwsdk.EVENT_TYPE_ERROR).process(a.info);this._rendererState.fail(this)}else{var c=this._inferEventType(b);if(c){if(c==_fwsdk.EVENT_TYPE_CLICK&&a.info&&a.info[_fwsdk.INFO_KEY_CUSTOM_EVENT_NAME])b=a.info[_fwsdk.INFO_KEY_CUSTOM_EVENT_NAME];(b=this._adInstance.getEventCallback(b,c))&&b.process(a.info)}}},setCapability:function(a,b){this._adInstance.setMetr(a,b)},getVersion:function(){return this._adManager.getVersion()},getParameter:function(a){if(!a)return null;if(this._adManager._overrideLevelParameterDictionary.hasOwnProperty(a))return this._overrideLevelParameterDictionary[a];
if(this._adInstance._primaryCreativeRendition&&this._adInstance._primaryCreativeRendition._parameters.hasOwnProperty(a))return this._adInstance._primaryCreativeRendition._parameters[a];var b=this._adManager._adResponse.getCreative(this._adInstance._adId,this._adInstance._creativeId);if(b&&b._parameters.hasOwnProperty(a))return b._parameters[a];if(this._adInstance.getSlot()._parameters.hasOwnProperty(a))return this._slot._parameters[a];if(this._adManager._globalLevelParameterDictionary.hasOwnProperty(a))return this._globalLevelParameterDictionary[a];
return null},scheduleAdInstances:function(a){a=a||[];var b=[];if(a.length===0)return b;var c=a[0],d=c._currentAdInstance;c=c.scheduleAdInstance();b.push(c);var e=0;for(d=d._companionAdInstances;e<d.length;e++)for(var f=d[e],h=1;h<a.length;h++)if(a[h]==f._slot){f=f.schedule();c._companionAdInstances.push(f);b.push(f);break}return b},playable:function(){return this._rendererState==_fwsdk.RendererInitState.instance},reset:function(){this._rendererState=_fwsdk.RendererInitState.instance},play:function(){var a=
_fwsdk.Util.getObject(this._matchRendererClassName(this._adInstance._primaryCreativeRendition));if(a)this._renderer=new a;this._renderer?this._rendererState.start(this):this.processEvent({name:_fwsdk.RENDERER_STATE_FAILED,info:{errorCode:_fwsdk.ERROR_NO_RENDERER}})},_matchRendererClassName:function(a){var b=a.getContentType();a=a.getWrapperType();if(_fwsdk.Util.isBlank(b)&&_fwsdk.Util.isBlank(a))return null;(a=this._adManager._rendererManifest["*"])||(a=this._adManager._rendererManifest[b]);if(a)return a;
a=this._adInstance.getSlot();var c=a.getType();if(b=="null/null")return"_fwsdk.NullAdRenderer";else if(c==_fwsdk.SLOT_TYPE_SITESECTION_NONTEMPORAL||c==_fwsdk.SLOT_TYPE_VIDEOPLAYER_NONTEMPORAL)return"_fwsdk.DisplayAdRenderer";else if(c==_fwsdk.SLOT_TYPE_TEMPORAL)return a.getTimePositionClass()==_fwsdk.TIME_POSITION_CLASS_OVERLAY?"_fwsdk.OverlayAdRenderer":"_fwsdk.VideoAdRenderer";return null},_inferEventType:function(a){if(a==_fwsdk.EVENT_ERROR)return _fwsdk.EVENT_TYPE_ERROR;else if(a==_fwsdk.EVENT_AD_CLICK)return _fwsdk.EVENT_TYPE_CLICK;
else if(a==_fwsdk.EVENT_AD_IMPRESSION||a==_fwsdk.EVENT_AD_FIRST_QUARTILE||a==_fwsdk.EVENT_AD_MIDPOINT||a==_fwsdk.EVENT_AD_THIRD_QUARTILE||a==_fwsdk.EVENT_AD_COMPLETE||a==_fwsdk.EVENT_RESELLER_NO_AD)return _fwsdk.EVENT_TYPE_IMPRESSION;else if(a==_fwsdk.EVENT_AD_PAUSE||a==_fwsdk.EVENT_AD_RESUME||a==_fwsdk.EVENT_AD_REWIND||a==_fwsdk.EVENT_AD_MUTE||a==_fwsdk.EVENT_AD_UNMUTE||a==_fwsdk.EVENT_AD_COLLAPSE||a==_fwsdk.EVENT_AD_EXPAND||a==_fwsdk.EVENT_AD_MINIMIZE||a==_fwsdk.EVENT_AD_CLOSE||a==_fwsdk.EVENT_AD_ACCEPT_INVITATION)return _fwsdk.EVENT_TYPE_STANDARD;
return null}});_fwsdk.PageSlotScanner=function(){this._knownSlots=[];this._slots={}};
_fwsdk.PageSlotScanner.prototype={isSlotDuplicate:function(a){for(var b=0;b<this._knownSlots.length;++b)if(this._knownSlots[b]==a)return true;return false},findPageSlotByScope:function(a){for(var b,c=/(^|\s)_fwph(\s|$)/,d=a.getElementsByTagName("span"),e=0;e<d.length;++e){var f;b=d[e];if(c.test(b.className)){b=b.getAttribute("id");if((f=a.getElementById("_fw_input_"+b))&&!this.isSlotDuplicate(b))if(f=f.getAttribute("value")){if(f.charAt(f.length-1)!=";")f+=";";f=f.split(";");var h=f[f.length-2];f=
false;if(h.search("lo=i")!=-1)f=true;var k=false,m=false;if(h.search("prct=")!=-1)m=true;if(h.search("flag=")!=-1)k=true;if(h.search("ptgt=")<0)h="ptgt=s&"+h;var g="",l=[];h=h.split("&");for(var j,o=0;o<h.length;++o){j=h[o].split("=");if(j.length==2){if(j[0]=="ssct")if(m)continue;else{m=true;j[0]="prct"}else if(j[0]=="sflg")if(k){if(j[1].charAt(0)!="+"&&j[1].charAt(0)!="-")j[1]="+"+j[1];g=j[1];continue}else j[0]="flag";if(j[0]=="flag"){if(g.length>0)j[1]+=g;if(j[1].charAt(0)!="+"&&j[1].charAt(0)!=
"-")j[1]="+"+j[1];if(f&&j[1].search("-init")==-1)j[1]+="-init";if(j[1].search("-nrpl")!=-1)j[1]=j[1].replace("-nrpl","+cmpn")}j=encodeURIComponent(j[0])+"="+encodeURIComponent(j[1]);l.push(j)}}m||l.push("prct="+encodeURIComponent("text/html_lit_js_wc_nw"));this._slots[b]=l.join("&")+";";this._knownSlots.push(b)}}}},scanPageSlots:function(){for(var a=0;a<window.frames.length;++a)try{this.findPageSlotByScope(window.frames[a].document)}catch(b){}try{this.findPageSlotByScope(parent.document)}catch(c){}try{this.findPageSlotByScope(document)}catch(d){}},
slotsToTypeBStr:function(){var a="";for(slotId in this._slots)if(!Object[slotId]){var b=this._slots[slotId];if(b.search("slid=")==-1)b="slid="+encodeURIComponent(slotId)+"&"+b;a+=b;if(a.charAt(a.length-1)!=";")a+=";"}return a}};_fwsdk.PageSlotScanner.prototype.constructor=_fwsdk.PageSlotScanner;_fwsdk.AdResponse=function(a){this._adManager=a};_fwsdk.AdResponse.prototype={};_fwsdk.AdResponse.prototype.constructor=_fwsdk.AdResponse;
_fwsdk.Util.mixin(_fwsdk.AdResponse.prototype,{parse:function(a,b,c){this._data=a;this._temporalSlots=[];this._videoPlayerNonTemporalSlots=[];this._siteSectionNonTemporalSlots=[];this._knownPageSlots=c;this._ads=[];var d;d=_fwsdk.Util.getObject("ads.ads",a)||[];for(c=0;c<d.length;++c){var e=new _fwsdk.Ad(this._adManager);e.parse(d[c]);this._ads.push(e)}d=_fwsdk.Util.getObject("siteSection.videoPlayer.videoAsset.adSlots",a)||[];for(c=0;c<d.length;++c){e=new _fwsdk.Slot(this._adManager);e._type=_fwsdk.SLOT_TYPE_TEMPORAL;
e._baseId=b;e.parse(d[c]);this._temporalSlots.push(e)}d=_fwsdk.Util.getObject("siteSection.videoPlayer.adSlots",a)||[];for(c=0;c<d.length;++c){e=new _fwsdk.Slot(this._adManager);e._type=_fwsdk.SLOT_TYPE_VIDEOPLAYER_NONTEMPORAL;e.parse(d[c]);this._videoPlayerNonTemporalSlots.push(e)}d=_fwsdk.Util.getObject("siteSection.adSlots",a)||[];for(c=0;c<d.length;++c){e=new _fwsdk.Slot(this._adManager);e._type=_fwsdk.SLOT_TYPE_SITESECTION_NONTEMPORAL;e.parse(d[c]);this._siteSectionNonTemporalSlots.push(e)}if(this._knownPageSlots)for(c=
0;c<this._knownPageSlots.length;++c)if(!this.getSlotByCustomId(this._knownPageSlots[c])){e=new _fwsdk.Slot(this._adManager);e._type=_fwsdk.SLOT_TYPE_SITESECTION_NONTEMPORAL;e.parse({customId:this._knownPageSlots[c],eventCallbacks:[],selectedAds:[]});this._siteSectionNonTemporalSlots.push(e)}},getCreativeRendition:function(a,b,c){return(a=this.getCreative(a,b))?a.getCreativeRendition(c):null},getCreative:function(a,b){for(var c=0;c<this._ads.length;c++){var d=this._ads[c];if(d._id==a)return d.getCreative(b)}return null},
getSiteSectionNonTemporalSlots:function(){return this._siteSectionNonTemporalSlots},getVideoPlayerNonTemporalSlots:function(){return this._videoPlayerNonTemporalSlots},getSlotByCustomId:function(a){for(var b=0;b<this._temporalSlots.length;++b)if(this._temporalSlots[b]._customId==a)return this._temporalSlots[b];for(b=0;b<this._videoPlayerNonTemporalSlots.length;++b)if(this._videoPlayerNonTemporalSlots[b]._customId==a)return this._videoPlayerNonTemporalSlots[b];for(b=0;b<this._siteSectionNonTemporalSlots.length;++b)if(this._siteSectionNonTemporalSlots[b]._customId==
a)return this._siteSectionNonTemporalSlots[b];_fwsdk.log("getSlotByCustomId(): not found",a);return null},registerSlotEndCallback:function(a){for(var b=0;b<this._temporalSlots.length;++b)this._temporalSlots[b]._onSlotEnd=a}});
_fwsdk.AdInstance=function(a){this._adManager=a;this._primaryCreativeRendition=this._replicaId=this._creativeRenditionId=this._creativeId=this._adId=this._slot=null;this._companionAdInstances=[];this._eventCallbacks=[];this._externalEventCallbackUrlsDictionary={};this._rendererController=new _fwsdk.RendererController(this._adManager);this._rendererController._adInstance=this;this._timer=new _fwsdk.Timer;this._metr=0;this._state=_fwsdk.MediaInitState.instance};_fwsdk.AdInstance.prototype={};
_fwsdk.AdInstance.prototype.constructor=_fwsdk.AdInstance;_fwsdk.METR_MASK_QUARTILE=0;_fwsdk.METR_MASK_MIDPOINT=1;_fwsdk.METR_MASK_COMPLETE=2;_fwsdk.METR_MASK_VOLUME=3;_fwsdk.METR_MASK_SIZE=4;_fwsdk.METR_MASK_CONTROL=5;_fwsdk.METR_MASK_REWIND=6;_fwsdk.METR_MASK_ACCEPT_INVITATION=7;_fwsdk.METR_MASK_CLOSE=8;_fwsdk.METR_MASK_MINIMIZE=9;_fwsdk.METR_MASK_CLICK=10;_fwsdk.AdInstance._metrDictionary={};
_fwsdk.AdInstance._metrDictionary[_fwsdk.EVENT_AD_QUARTILE]=1<<_fwsdk.METR_MASK_QUARTILE|1<<_fwsdk.METR_MASK_MIDPOINT|1<<_fwsdk.METR_MASK_COMPLETE;_fwsdk.AdInstance._metrDictionary[_fwsdk.EVENT_AD_MIDPOINT]=1<<_fwsdk.METR_MASK_MIDPOINT|1<<_fwsdk.METR_MASK_COMPLETE;_fwsdk.AdInstance._metrDictionary[_fwsdk.EVENT_AD_COMPLETE]=1<<_fwsdk.METR_MASK_COMPLETE;_fwsdk.AdInstance._metrDictionary[_fwsdk.EVENT_AD_MUTE]=1<<_fwsdk.METR_MASK_VOLUME;_fwsdk.AdInstance._metrDictionary[_fwsdk.EVENT_AD_UNMUTE]=1<<_fwsdk.METR_MASK_VOLUME;
_fwsdk.AdInstance._metrDictionary[_fwsdk.EVENT_AD_COLLAPSE]=1<<_fwsdk.METR_MASK_SIZE;_fwsdk.AdInstance._metrDictionary[_fwsdk.EVENT_AD_EXPAND]=1<<_fwsdk.METR_MASK_SIZE;_fwsdk.AdInstance._metrDictionary[_fwsdk.EVENT_AD_PAUSE]=1<<_fwsdk.METR_MASK_CONTROL;_fwsdk.AdInstance._metrDictionary[_fwsdk.EVENT_AD_RESUME]=1<<_fwsdk.METR_MASK_CONTROL;_fwsdk.AdInstance._metrDictionary[_fwsdk.EVENT_AD_REWIND]=1<<_fwsdk.METR_MASK_REWIND;_fwsdk.AdInstance._metrDictionary[_fwsdk.EVENT_AD_ACCEPT_INVITATION]=1<<_fwsdk.METR_MASK_ACCEPT_INVITATION;
_fwsdk.AdInstance._metrDictionary[_fwsdk.EVENT_AD_CLOSE]=1<<_fwsdk.METR_MASK_CLOSE;_fwsdk.AdInstance._metrDictionary[_fwsdk.EVENT_AD_MINIMIZE]=1<<_fwsdk.METR_MASK_MINIMIZE;_fwsdk.AdInstance._metrDictionary[_fwsdk.EVENT_AD_CLICK]=1<<_fwsdk.METR_MASK_CLICK;
_fwsdk.Util.mixin(_fwsdk.AdInstance.prototype,{getAdId:function(){return this._adId},getEventCallbackUrls:function(a,b){var c=[],d=b==_fwsdk.EVENT_TYPE_CLICK,e=b==_fwsdk.EVENT_TYPE_CLICK_TRACKING,f=_fwsdk.EventCallback.getEventCallback(this._eventCallbacks,a,e?_fwsdk.EVENT_TYPE_CLICK:b);if(!f)return c;e||c.push(f.getUrl());if(!d){d=0;for(f=f._trackingUrls;d<f.length;d++)c.push(f[d]);d=0;for(f=this.getExternalEventCallbackUrls(a,b);d<f.length;d++)c.push(f[d])}return c},addEventCallbackUrls:function(a,
b,c){if(c&&this._isValidEventNameAndType(a,b))if(b==_fwsdk.EVENT_TYPE_CLICK)this.getEventCallback(a,b).setUrlParameter(_fwsdk.URL_PARAMETER_KEY_CR,c.length>0?c[0]:"");else{for(var d=this._externalEventCallbackUrlsDictionary[b+"-"+a]||[],e=0;e<c.length;e++)d.push(c[e]);this._externalEventCallbackUrlsDictionary[b+"-"+a]=d}},schedule:function(){var a=new _fwsdk.AdInstance(this._adManager);a._parent=this;a._adId=this._adId;a._creativeId=this._creativeId;a._slot=this.getSlot();for(var b=0;b<this._eventCallbacks.length;b++){var c=
this._eventCallbacks[b].copy();c._adInstance=a;a._eventCallbacks.push(c)}a._externalEventCallbackUrlsDictionary=_fwsdk.Util.copy(this._externalEventCallbackUrlsDictionary);return a},addCreativeRendition:function(){if(!this._primaryCreativeRendition){this._primaryCreativeRendition=new _fwsdk.CreativeRendition(this._adManager);this._primaryCreativeRendition._parameters=_fwsdk.Util.copy(this._parent._primaryCreativeRendition._parameters);return this._primaryCreativeRendition}return null},getSlot:function(){if(!this._slot)this._slot=
this._adManager._adResponse.getSlotByCustomId(this._slotCustomId);return this._slot},getCompanionSlots:function(){for(var a=[],b=0;b<this._companionAdInstances.length;b++)a.push(this._companionAdInstances[b]._slot);return a},getPrimaryCreativeRendition:function(){return this._primaryCreativeRendition},setPrimaryCreativeRendition:function(a){this._primaryCreativeRendition=a},getOtherCreativeRenditions:function(){var a=this._adManager._adResponse.getCreative(this._adId,this._creativeId);if(!a)return[];
for(var b=[],c=0;c<a._creativeRenditions.length;c++){var d=a._creativeRenditions[c];d!==this._primaryCreativeRendition&&b.push(d)}return b},parse:function(a){this._adId=a.adId;this._creativeId=a.creativeId;this._creativeRenditionId=a.creativeRenditionId;this._replicaId=a.replicaId;this._primaryCreativeRendition=this._adManager._adResponse.getCreativeRendition(this._adId,this._creativeId,this._creativeRenditionId);for(var b=0,c=a.eventCallbacks||[];b<c.length;b++){var d=c[b],e=_fwsdk.EventCallback.newEventCallback(this._adManager,
d.name,d.type);if(e){e._adInstance=this;e.parse(d);this._eventCallbacks.push(e)}}b=0;for(c=a.companionAds||[];b<c.length;++b)if((d=c[b])&&d.adSlotCustomId){a=new _fwsdk.AdInstance(this._adManager);a._slotCustomId=d.adSlotCustomId;a.parse(d);this._companionAdInstances.push(a)}},play:function(){this._state.play(this);if(_fwsdk.MODULE_TYPE_RENDERER==this._rendererController._renderer.info()[_fwsdk.INFO_KEY_MODULE_TYPE])for(var a=0;a<this._companionAdInstances.length;a++)this._companionAdInstances[a]._rendererController.play()},
complete:function(){this._state.complete(this);this._rendererController._renderer=null;this._slot.playNextAdInstance()},onStartPlaying:function(){this._timer.tick();var a=this.getEventCallback(_fwsdk.EVENT_AD_IMPRESSION,_fwsdk.EVENT_TYPE_IMPRESSION);if(this._slot._type==_fwsdk.SLOT_TYPE_TEMPORAL){this._init="1";this._last="0"}else this._last=this._init="1";a&&a.process()},onCompletePlaying:function(){if(this._slot._type==_fwsdk.SLOT_TYPE_TEMPORAL){this._init="0";this._last="1";var a=this.getEventCallback(_fwsdk.EVENT_AD_IMPRESSION,
_fwsdk.EVENT_TYPE_IMPRESSION);a&&a.process()}},onStartReplaying:function(){this._timer.tick();var a=this.getEventCallback(_fwsdk.EVENT_AD_IMPRESSION,_fwsdk.EVENT_TYPE_IMPRESSION);if(this._slot._type==_fwsdk.SLOT_TYPE_TEMPORAL){this._init="2";this._last="0"}else{this._init="2";this._last="1"}a&&a.process()},onCompleteReplaying:function(){if(this._slot._type==_fwsdk.SLOT_TYPE_TEMPORAL){this._init="2";this._last="1";var a=this.getEventCallback(_fwsdk.EVENT_AD_IMPRESSION,_fwsdk.EVENT_TYPE_IMPRESSION);
a&&a.process()}},getEventCallback:function(a,b){return _fwsdk.EventCallback.getEventCallback(this._eventCallbacks,a,b)},setMetr:function(a,b){var c=_fwsdk.AdInstance._metrDictionary[a];if(c){if(a==_fwsdk.EVENT_AD_CLICK)b=!b;if(b==_fwsdk.CAPABILITY_STATUS_ON)this._metr|=c;else this._metr&=~c}},getExternalEventCallbackUrls:function(a,b){return this._externalEventCallbackUrlsDictionary[b+"-"+a]||[]},_isValidEventNameAndType:function(a,b){if(_fwsdk.Util.isBlank(a)||_fwsdk.Util.isBlank(b))return false;
return b==_fwsdk.EVENT_TYPE_CLICK||b==_fwsdk.EVENT_TYPE_CLICK_TRACKING||b==_fwsdk.EVENT_TYPE_IMPRESSION&&(a==_fwsdk.EVENT_AD_IMPRESSION||a==_fwsdk.EVENT_AD_FIRST_QUARTILE||a==_fwsdk.EVENT_AD_MIDPOINT||a==_fwsdk.EVENT_AD_THIRD_QUARTILE||a==_fwsdk.EVENT_AD_COMPLETE)||b==_fwsdk.EVENT_TYPE_STANDARD&&(a==_fwsdk.EVENT_AD_PAUSE||a==_fwsdk.EVENT_AD_RESUME||a==_fwsdk.EVENT_AD_REWIND||a==_fwsdk.EVENT_AD_MUTE||a==_fwsdk.EVENT_AD_UNMUTE||a==_fwsdk.EVENT_AD_COLLAPSE||a==_fwsdk.EVENT_AD_EXPAND||a==_fwsdk.EVENT_AD_MINIMIZE||
a==_fwsdk.EVENT_AD_CLOSE||a==_fwsdk.EVENT_AD_ACCEPT_INVITATION)},toString:function(){return"[AdInstance "+this._adId+"]"}});_fwsdk.Timer=function(){this._lastTickDate=new Date};_fwsdk.Timer.prototype={};_fwsdk.Timer.prototype.constructor=_fwsdk.Timer;_fwsdk.Util.mixin(_fwsdk.Timer.prototype,{tick:function(){var a=new Date,b=Math.round((a.getTime()-this._lastTickDate.getTime())/1E3);this._lastTickDate=a;return b},pause:function(){},resume:function(){}});
_fwsdk.AdRequest=function(a){this._assetNetworkId=this._assetDuration=this._assetCustomId=this._assetId="";this._assetAutoPlay=true;this._assetFallbackId=0;this._siteSectionNetwrokId=this._siteSectionId=this._siteSectionCustomId="";this._siteSectionFallbackId=0;this._keyValues={};this._slotScanner=new _fwsdk.PageSlotScanner;this._urlParams={};this._customInfo=this._kvString="";this._instanceId=a;this._compatibleDimensions=null};
_fwsdk.AdRequest.prototype={addKeyValue:function(a,b){if(!(!a||!b||typeof a!="string"||typeof b!="string"||a.length==0)){if(this._keyValues[a]==undefined)this._keyValues[a]={};this._keyValues[a][b]=""}},toKeyValueStr:function(){var a="";for(key in this._keyValues)if(!Object[key]){var b=this._keyValues[key];for(value in b)Object[value]||(a+=key+"="+value+"&")}a=a.substring(0,a.lastIndexOf("&"));return a+";"},setVideoAsset:function(a,b,c,d,e,f){if(a){if(!e||typeof e!="number")this._assetCustomId=a;
else switch(e){case 1:this._assetId=a;break;case 2:this._assetId="g"+a;break;default:this._assetCustomId=a;break}if(b&&typeof b=="number")this._assetDuration=b;if(c&&typeof c=="boolean")this._assetAutoPlay=c;if(d&&typeof d=="number")this._assetNetworkId=d;if(f&&typeof f=="number")this._assetFallbackId=f}else _fwsdk.log("AdManager.setVideoAsset(): id required")},setSiteSection:function(a,b,c,d){if(a){if(!c||typeof c!="number")this._siteSectionCustomId=a;else switch(c){case 1:this._siteSectionId=a;
break;case 2:this._siteSectionId="g"+a;break;default:this._siteSectionCustomId=a;break}if(b&&typeof b=="number")this._siteSectionNetwrokId=b;if(d&&typeof d=="number")this._siteSectionFallbackId=d}else _fwsdk.log("AdManager.setSiteSection(): id required")},parseQueryStr:function(a){if(a){if(a.charAt(a.length-1)==";")a=a.substring(0,a.length-1);a=a.split(";");for(var b=a[0].split("&"),c,d=0;d<b.length;++d){c=b[d].split("=");if(c.length==2)this._urlParams[c[0]]=c[1]}if(a[1])this._kvString=a[1];if(a[2])for(d=
2;d<a.length;++d)this._customInfo+=a[d]+";"}},generateQueryStr:function(){if(this._assetCustomId)this._urlParams.caid=encodeURIComponent(this._assetCustomId+"");if(this._assetDuration>0)this._urlParams.vdur=this._assetDuration;if(this._siteSectionCustomId)this._urlParams.csid=encodeURIComponent(this._siteSectionCustomId+"");this._urlParams.cd=this._compatibleDimensions?encodeURIComponent(this._compatibleDimensions):encodeURIComponent(this.detectScreenDimension());this._urlParams.vclr=encodeURIComponent(_fwsdk.version);
this._urlParams.resp="json";this._urlParams.cbfn=encodeURIComponent("tv.freewheel.SDK._instanceQueue['AdManager_"+this._instanceId+"'].requestCallback");var a="";for(key in this._urlParams)Object[key]||(a+=key+"="+this._urlParams[key]+"&");a=a.substring(0,a.length-1);a=this.setCapabilities(a);return a+";"},setCapabilities:function(a){a=a;var b=encodeURIComponent("+exvt+unka+unks+emcr+slcb+sltp+nucr");a=a.replace(/(%2B|-|\+)(exvt|unka|unks|emcr|slcb|sltp|nucr)/g,"");if(a.indexOf("flag=")>-1)a=a.replace(/flag=/,
"flag="+b);else a+="&flag="+b;return a},scanPageSlots:function(){this._slotScanner.scanPageSlots()},toTypeBStr:function(){var a="";if(this._kvString.length>0)this._kvString="&"+this._kvString;this._kvString="_fw_h_x_flash_version="+encodeURIComponent("0,0,0,0")+this._kvString;a+=this.generateQueryStr()+this._kvString+";"+this._slotScanner.slotsToTypeBStr();if(this._customInfo.length>0)a+=this._customInfo;return a},setVideoDisplayCompatibleSizes:function(a){_fwsdk.log("setVideoDisplayCompatibleSizes",
a);if(a&&a.length){for(var b=[],c={},d=0;d<a.length;++d){_fwsdk.log("dimension is:",a[d].width,"X",a[d].height);if(a[d].width>0&&a[d].height>0){var e=a[d].width+","+a[d].height;if(c[e]==null){c[e]="";b.push(e)}}}if(b.length>0)this._compatibleDimensions=b.join("|")}},detectScreenDimension:function(){return screen.width+","+screen.height}};_fwsdk.RenditionSelector=function(a,b,c,d){this._targetByterate=a;this._arWeight=b;this._pxWeight=c;this._conversionFactor=d};
_fwsdk.RenditionSelector.prototype={getBestFitRendition:function(a,b,c){a=this.filterRenditionsByBitrate(a,this._targetByterate);if(a.length>0){for(var d=a[0],e=1;e<a.length;++e){var f=this.compareVisualMetrics(d,a[e],b,c);if(f)d=f}return d}return null},filterRenditionsByBitrate:function(a,b){for(var c=[],d,e=0;e<a.length;++e)if(this.validateCreativeRendition(a[e]))if(this.getBitrate(a[e])<=b)c.push(a[e]);else if(!d||this.getBitrate(a[e])<this.getBitrate(d))d=a[e];c.length===0&&d&&c.push(d);var f=
this;c.sort(function(h,k){return f.sortOnBitrate(h,k)});return c},compareVisualMetrics:function(a,b,c,d){var e=this.calculateVisualRatios(a._width,a._height,c,d);d=this.calculateVisualRatios(b._width,b._height,c,d);if(!e&&d)return b;if(e&&!d)return a;if(!e&&!d)return null;c=this._conversionFactor*this._arWeight*Math.log(e.arRatio);var f=this._pxWeight*Math.log(e.pixelation);e=this._conversionFactor*this._arWeight*Math.log(d.arRatio);d=this._pxWeight*Math.log(d.pixelation);c=this.findDistance(c,f,
0,0);e=this.findDistance(e,d,0,0);if(c==e)return null;return c<e?a:b},calculateVisualRatios:function(a,b,c,d){if(a>0&&b>0&&c>0&&d>0){var e=a/b,f=c/d;a=a*b;if(e>f){c=c;d=c/e}else{d=d;c=d*e}return{arRatio:e/f,pixelation:a/(c*d)}}return null},findDistance:function(a,b,c,d){return isNaN(a)||isNaN(c)||isNaN(b)||isNaN(d)?NaN:Math.sqrt(Math.pow(c-a,2)+Math.pow(d-b,2))},validateCreativeRendition:function(a){if(!a)return false;a=a._primaryCreativeRenditionAsset;if(!a)return false;if(_fwsdk.Util.isBlank(a._url)&&
_fwsdk.Util.isBlank(a._content))return false;return true},validateProtocol:function(a){for(var b=["http","https","rtmp"],c=0;c<b.length;++c)if(a.toLowerCase().indexOf(b[c]+"://")===0)return true;return false},sortOnBitrate:function(a,b){a=this.getBitrate(a);b=this.getBitrate(b);return a>b?-1:a<b?1:0},getBitrate:function(a){var b=a.getDuration();return(a=a._primaryCreativeRenditionAsset._bytes)&&b&&!isNaN(a)&&!isNaN(b)&&a>0&&b>0?a*8/1E3/b:-1}};_fwsdk.RenditionSelector.prototype.constructor=_fwsdk.RenditionSelector;
_fwsdk.DisplayAdRenderer=function(){};
_fwsdk.DisplayAdRenderer.prototype={start:function(a){var b=a.getAdInstance(),c=b.getSlot()._customId;if(b=b.getPrimaryCreativeRendition().getPrimaryCreativeRenditionAsset().getContent()){var d=null,e=null;try{if(document.getElementById(c)){d=document;e="document"}else if(parent.document.getElementById(c)){d=parent.document;e="parent.document"}}catch(f){}if(!d)for(var h=0;h<window.frames.length;++h)try{if(window.frames[h].document.getElementById(c)){d=window.frames[h].document;e="window.frames["+
h+"].document";break}}catch(k){}if(d){c=d.getElementById("_fw_container_"+c);_fwsdk.Util.buildNode(c,b,e);a.processEvent({name:_fwsdk.RENDERER_STATE_STARTED})}else a.processEvent({name:_fwsdk.RENDERER_STATE_FAILED,info:{errorModule:"DisplayAdRenderer",errorInfo:"can not find scope on page"}})}else a.processEvent({name:_fwsdk.RENDERER_STATE_FAILED,info:{errorModule:"DisplayAdRenderer",errorCode:_fwsdk.ERROR_NULL_ASSET}})},info:function(){return{moduleType:_fwsdk.MODULE_TYPE_RENDERER}}};
_fwsdk.DisplayAdRenderer.prototype.constructor=_fwsdk.DisplayAdRenderer;_fwsdk.EventCallback=function(){this._url=this._name=this._type=null;this._showBrowser=false;this._trackingUrls=[];this._adInstance=this._slot=null};_fwsdk.EventCallback.prototype={};_fwsdk.EventCallback.prototype.constructor=_fwsdk.EventCallback;
_fwsdk.EventCallback.getEventCallback=function(a,b,c){for(var d=0;d<a.length;d++){var e=a[d];if(e._name==b&&e._type==c)return e}for(d=0;d<a.length;d++){e=a[d];if(e._type==_fwsdk.EVENT_TYPE_GENERIC){b=_fwsdk.EventCallback.newEventCallback(e._adManager,b,c);b.setUrl(e.getUrl());b._slot=e._slot;b._adInstance=e._adInstance;b&&a.push(b);return b}}return null};
_fwsdk.EventCallback.newEventCallback=function(a,b,c){var d=null;if(c==_fwsdk.EVENT_TYPE_GENERIC)d=new _fwsdk.EventCallback(a);else if(c==_fwsdk.EVENT_TYPE_ERROR)d=new _fwsdk.ErrorEventCallback(a);else if(c==_fwsdk.EVENT_TYPE_CLICK)d=new _fwsdk.AdClickEventCallback(a);else if(c==_fwsdk.EVENT_TYPE_STANDARD)d=new _fwsdk.AdStandardEventCallback(a);else if(b==_fwsdk.EVENT_SLOT_IMPRESSION)d=new _fwsdk.SlotImpressionEventCallback(a);else if(b==_fwsdk.EVENT_AD_IMPRESSION)d=new _fwsdk.AdImpressionEventCallback(a);
else if(b==_fwsdk.EVENT_VIDEO_VIEW)d=new _fwsdk.VideoViewEventCallback(a);else if(b==_fwsdk.EVENT_RESELLER_NO_AD)d=new _fwsdk.ResellerNoAdEventCallback(a);else if(b==_fwsdk.EVENT_AD_FIRST_QUARTILE||b==_fwsdk.EVENT_AD_MIDPOINT||b==_fwsdk.EVENT_AD_THIRD_QUARTILE||b==_fwsdk.EVENT_AD_COMPLETE)d=new _fwsdk.AdQuartileEventCallback(a);else return null;d._name=b;d._type=c;return d};
_fwsdk.Util.mixin(_fwsdk.EventCallback.prototype,{parse:function(a){this._usage=a.use;this._type=a.type;this._name=a.name;this.setUrl(a.url);this._showBrowser=a.showBrowser;this._trackingUrls=[];var b=0;for(a=a.trackingUrls||[];b<a.length;b++)this._trackingUrls.push(a[b].value)},copy:function(){var a=new this.constructor(this._adManager);a._type=this._type;a._name=this._name;a.setUrl(this.getInternalUrl());a._showBrowser=this._showBrowser;a._trackingUrls=this._trackingUrls.slice();a._slot=this._slot;
a._adInstance=this._adInstance;return a},getUrl:function(){this._url.setParameter(_fwsdk.URL_PARAMETER_KEY_ET,this._getShortType());this._url.setParameter(_fwsdk.URL_PARAMETER_KEY_CN,this._name);return this._url.toString()},setUrl:function(a){this._originalUrl=a;this._url=new _fwsdk.Url(a)},getUrlParameter:function(a){return this._url?this._url.getParameter(a):null},setUrlParameter:function(a,b){this._url&&this._url.setParameter(a,b)},process:function(a){a=a||{};this._prepareUrlParameters(a);this._send(a)},
getInternalUrl:function(){var a=new _fwsdk.Url(this._originalUrl);a.setParameter(_fwsdk.URL_PARAMETER_KEY_ET,this._getShortType());a.setParameter(_fwsdk.URL_PARAMETER_KEY_CN,this._name);var b=this.getUrlParameter(_fwsdk.URL_PARAMETER_KEY_CR);b&&a.setParameter(_fwsdk.URL_PARAMETER_KEY_CR,b);return a.toString()},_prepareUrlParameters:function(){},_shouldSkipSendingTrackingAndExternalUrls:function(){return false},_send:function(){if(!this._shouldSkipSendingTrackingAndExternalUrls()){_fwsdk.Util.pingURLs(this._trackingUrls);
this._adInstance&&_fwsdk.Util.pingURLs(this._adInstance.getExternalEventCallbackUrls(this._name,this._type))}_fwsdk.Util.pingURL(this.getUrl())},_getShortType:function(){return this._type==_fwsdk.EVENT_TYPE_IMPRESSION?_fwsdk.SHORT_EVENT_TYPE_IMPRESSION:this._type==_fwsdk.EVENT_TYPE_CLICK?_fwsdk.SHORT_EVENT_TYPE_CLICK:this._type==_fwsdk.EVENT_TYPE_STANDARD?_fwsdk.SHORT_EVENT_TYPE_STANDARD:this._type==_fwsdk.EVENT_TYPE_ERROR?_fwsdk.SHORT_EVENT_TYPE_ERROR:""}});_fwsdk.AdClickEventCallback=function(){};
_fwsdk.AdClickEventCallback.prototype=new _fwsdk.EventCallback;_fwsdk.AdClickEventCallback.prototype.constructor=_fwsdk.AdClickEventCallback;
_fwsdk.Util.mixin(_fwsdk.AdClickEventCallback.prototype,{_send:function(a){var b,c;if(_fwsdk.Util.isBlank(b)){b=_fwsdk.EVENT_AD_CLICK;c=this}else{b=a[_fwsdk.INFO_KEY_CUSTOM_EVENT_NAME];c=_fwsdk.EventCallback.getEventCallback(this._adInstance._eventCallbacks,b,_fwsdk.EVENT_TYPE_CLICK)}var d=c.getUrl();_fwsdk.Util.pingURLs(c._trackingUrls);_fwsdk.Util.pingURLs(c._adInstance.getExternalEventCallbackUrls(b,_fwsdk.EVENT_TYPE_CLICK));(a.hasOwnProperty(_fwsdk.INFO_KEY_SHOW_BROWSER)?a[_fwsdk.INFO_KEY_SHOW_BROWSER]===
true:c._showBrowser===true)&&!_fwsdk.Util.isBlank(d)?window.open(d):_fwsdk.Util.pingURL(d)}});_fwsdk.AdImpressionEventCallback=function(){};_fwsdk.AdImpressionEventCallback.prototype=new _fwsdk.EventCallback;_fwsdk.AdImpressionEventCallback.prototype.constructor=_fwsdk.AdImpressionEventCallback;
_fwsdk.Util.mixin(_fwsdk.AdImpressionEventCallback.prototype,{_prepareUrlParameters:function(){this._url.setParameter(_fwsdk.URL_PARAMETER_KEY_METR,this._adInstance._metr);this._url.setParameter(_fwsdk.URL_PARAMETER_KEY_CT,this._adInstance._timer.tick());this._url.setParameter(_fwsdk.URL_PARAMETER_KEY_INIT,this._adInstance._init);this._url.setParameter(_fwsdk.URL_PARAMETER_KEY_LAST,this._adInstance._last)},_shouldSkipSendingTrackingAndExternalUrls:function(){return this._adInstance._init!="1"},process:function(a){_fwsdk.MODULE_TYPE_TRANSLATOR!=
this._adInstance._rendererController._renderer.info()[_fwsdk.INFO_KEY_MODULE_TYPE]&&_fwsdk.EventCallback.prototype.process.call(this,a)}});_fwsdk.AdQuartileEventCallback=function(){};_fwsdk.AdQuartileEventCallback.prototype=new _fwsdk.EventCallback;_fwsdk.AdQuartileEventCallback.prototype.constructor=_fwsdk.AdQuartileEventCallback;
_fwsdk.Util.mixin(_fwsdk.AdQuartileEventCallback.prototype,{_prepareUrlParameters:function(){this._url.setParameter(_fwsdk.URL_PARAMETER_KEY_METR,this._adInstance._metr);this._url.setParameter(_fwsdk.URL_PARAMETER_KEY_CT,this._adInstance._timer.tick())},process:function(a){if(!this._processed){this._processed=true;_fwsdk.EventCallback.prototype.process.call(this,a)}}});_fwsdk.AdStandardEventCallback=function(){};_fwsdk.AdStandardEventCallback.prototype=new _fwsdk.EventCallback;
_fwsdk.AdStandardEventCallback.prototype.constructor=_fwsdk.AdStandardEventCallback;_fwsdk.ErrorEventCallback=function(){};_fwsdk.ErrorEventCallback.prototype=new _fwsdk.EventCallback;_fwsdk.ErrorEventCallback.prototype.constructor=_fwsdk.ErrorEventCallback;
_fwsdk.Util.mixin(_fwsdk.ErrorEventCallback.prototype,{_prepareUrlParameters:function(a){_fwsdk.EventCallback.prototype._prepareUrlParameters();var b=a[_fwsdk.INFO_KEY_ERROR_CODE];if(!b)b=_fwsdk.ERROR_UNKNOWN;var c=a[_fwsdk.INFO_KEY_ERROR_INFO];c||(c="");(a=a[_fwsdk.INFO_KEY_ERROR_MODULE])||(a="");this._url.setParameter(_fwsdk.URL_PARAMETER_KEY_CN,b);this._url.setParameter(_fwsdk.URL_PARAMETER_KEY_ERROR_INFO,c);this._url.setParameter(_fwsdk.URL_PARAMETER_KEY_ERROR_MODULE,a)},getUrl:function(){this._url.setParameter(_fwsdk.URL_PARAMETER_KEY_ET,
this._getShortType());return this._url.toString()}});_fwsdk.ResellerNoAdEventCallback=function(){};_fwsdk.ResellerNoAdEventCallback.prototype=new _fwsdk.EventCallback;_fwsdk.ResellerNoAdEventCallback.prototype.constructor=_fwsdk.ResellerNoAdEventCallback;_fwsdk.Util.mixin(_fwsdk.ResellerNoAdEventCallback.prototype,{process:function(a){if(!this._processed){this._processed=true;_fwsdk.EventCallback.prototype.process.call(this,a)}}});_fwsdk.SlotImpressionEventCallback=function(){};
_fwsdk.SlotImpressionEventCallback.prototype=new _fwsdk.EventCallback;_fwsdk.SlotImpressionEventCallback.prototype.constructor=_fwsdk.SlotImpressionEventCallback;_fwsdk.Util.mixin(_fwsdk.SlotImpressionEventCallback.prototype,{_prepareUrlParameters:function(){this._url.setParameter(_fwsdk.URL_PARAMETER_KEY_INIT,this._slot._init)},_shouldSkipSendingTrackingAndExternalUrls:function(){return this._slot._init!="1"}});_fwsdk.VideoViewEventCallback=function(){};_fwsdk.VideoViewEventCallback.prototype=new _fwsdk.EventCallback;
_fwsdk.VideoViewEventCallback.prototype.constructor=_fwsdk.VideoViewEventCallback;_fwsdk.Util.mixin(_fwsdk.VideoViewEventCallback.prototype,{});
_fwsdk.AdManager=function(){this._serverURLOrigin=this._serverURL="";this._onRequestComplete=function(){};this._onSlotEnd=function(){};this._temporalSlotBaseId="";this._adRequest=new _fwsdk.AdRequest(_fwsdk._instanceCounter);this._timeOutId=this._adResponse=null;this._requestCompleted=false;this._requestId=_fwsdk._instanceCounter;this._rendererManifest={};this._globalLevelParameterDictionary={};this._overrideLevelParameterDictionary={};_fwsdk._instanceQueue["AdManager_"+_fwsdk._instanceCounter]=this;
++_fwsdk._instanceCounter};
_fwsdk.AdManager.prototype={setServerURL:function(a){_fwsdk.log("AdManager.setServerURL("+Array.prototype.slice.call(arguments).join(",")+")");if(!a||typeof a!="string")_fwsdk.log("AdManager.setServerURL(): url required");else{this._serverURLOrigin=a;var b=a.split("?");this._serverURL=b[0];b.length<2||this._adRequest.parseQueryStr(b.slice(1).join("?"))}},submitRequest:function(a,b){_fwsdk.log("AdManager.submitRequest()");if(!this._requestCompleted){if(a&&typeof a=="function")this._onRequestComplete=a;
else _fwsdk.log("this.adId submitRequest(): callback function required");this._adRequest.scanPageSlots();var c=document.getElementsByTagName("head")[0],d=document.createElement("script");if(this._serverURL.substring(this._serverURL.length-3,this._serverURL.length)==".js")d.src=this._serverURLOrigin;else if(_fwsdk.Debug!==null&&_fwsdk.Debug===true){_fwsdk.log("will send to regression Server");d.src=this._serverURL+"?session="+session_id+"&case="+case_id+";"+this._adRequest.toTypeBStr()}else d.src=
this._serverURL+"?"+this._adRequest.toTypeBStr();this._requestCompleted=false;d.onload=d.onreadystatechange=function(){if(!this.readyState||this.readyState=="loaded"||this.readyState=="complete")c.removeChild(d)};var e=this;b&&typeof b=="number"&&b>0||(b=5E3);var f=setTimeout(function(){_fwsdk.log("request timeout");clearTimeout(f);e.requestCallback(null)},b);this._timeOutId=f;_fwsdk.log("will send request to",d.src,"id",this._requestId,"timeout",b);c.appendChild(d)}},requestCallback:function(a){if(!this._requestCompleted){this._requestCompleted=
true;clearTimeout(this._timeOutId);var b=false;if(a!==null){_fwsdk._instanceQueue["AdManager_"+this._requestId]=null;this._adResponse=new _fwsdk.AdResponse(this);this._adResponse.parse(a,this._temporalSlotBaseId,this._adRequest._slotScanner._knownSlots);this._adResponse.registerSlotEndCallback(this._onSlotEnd);b=this._adResponse.getSiteSectionNonTemporalSlots();for(var c=0;c<b.length;++c)b[c].play();b=this._adResponse.getVideoPlayerNonTemporalSlots();for(c=0;c<b.length;++c)b[c].play();b=true}_fwsdk.log("request "+
(b?"success":"failed"));this._onRequestComplete({success:b,response:a});this._onRequestComplete=function(){}}},registerVideoDisplayBase:function(a){_fwsdk.log("AdManager.registerVideoDisplayBase("+Array.prototype.slice.call(arguments).join(",")+")");if(!a||typeof a!="string")_fwsdk.log("AdManager.registerVideoDisplayBase(): id required");else this._temporalSlotBaseId=a},setVideoAsset:function(a,b,c,d,e,f){_fwsdk.log("AdManager.setVideoAsset("+Array.prototype.slice.call(arguments).join(",")+")");this._adRequest.setVideoAsset(a,
b,c,d,e,f)},setSiteSection:function(a,b,c,d){_fwsdk.log("AdManager.setSiteSection("+Array.prototype.slice.call(arguments).join(",")+")");this._adRequest.setSiteSection(a,b,c,d)},addKeyValue:function(a,b){_fwsdk.log("AdManager.addKeyValue("+Array.prototype.slice.call(arguments).join(",")+")");this._adRequest.addKeyValue(a,b)},playSlots:function(a,b){_fwsdk.log("AdManager.playSlots("+a+")");if(typeof b!="function")b=function(){};if(this._adResponse){if(typeof a=="string")a=a.toUpperCase();for(var c=
[],d=0;d<this._adResponse._temporalSlots.length;++d){var e=this._adResponse._temporalSlots[d];if(Math.abs(e._timePosition-a)<0.1||a==e._timePositionClass.toUpperCase())c.push(e)}if(c.length===0){_fwsdk.log("AdManager.playSlots(): no slot matches",a);b()}else if(a==_fwsdk.TIME_POSITION_CLASS_OVERLAY||a==_fwsdk.TIME_POSITION_CLASS_MIDROLL)for(d=0;d<c.length;d++)(function(f){if(!f._onContentVideoTimeUpdate){var h=f.getBase().getElementsByTagName("video")[0],k=f._onContentVideoTimeUpdate=function(){if(!h.paused&&
h._fw_videoAdPlaying!==true&&h.currentTime-f._timePosition>=0&&h.currentTime-f._timePosition<1){h.removeEventListener("timeupdate",k,false);f.play(function(){var m=setInterval(function(){if(!h.paused&&h._fw_videoAdPlaying!==true&&Math.abs(h.currentTime-f._timePosition)>2){h.addEventListener("timeupdate",k,false);clearInterval(m)}},1E3)})}};h.addEventListener("timeupdate",k,false)}})(c[d]);else(function(){var f=c.shift();f?f.play(arguments.callee):b()})()}else{_fwsdk.log("no ad response");b()}},setParameter:function(a,
b,c){_fwsdk.log("AdManager.setParameter("+Array.prototype.slice.call(arguments).join(",")+")");if(c==_fwsdk.PARAMETER_LEVEL_GLOBAL)var d=this._globalLevelParameterDictionary;else if(c==_fwsdk.PARAMETER_LEVEL_OVERRIDE)d=this._overrideLevelParameterDictionary;else return;if(b)d[a]=b;else delete d[a]},getParameter:function(a){if(this._overrideLevelParameterDictionary.hasOwnProperty(a))return this._overrideLevelParameterDictionary[a];if(this._globalLevelParameterDictionary.hasOwnProperty(a))return this._globalLevelParameterDictionary[a];
return null},dispose:function(){_fwsdk.log("AdManager.dispose()");if(this._adResponse)for(var a=0,b=this._adResponse._temporalSlots||[];a<b.length;++a){var c=b[a];if(c._onContentVideoTimeUpdate){c.getBase().getElementsByTagName("video")[0].removeEventListener("timeupdate",c._onContentVideoTimeUpdate,false);c._onContentVideoTimeUpdate=null}}},setVideoDisplayCompatibleSizes:function(a){this._adRequest.setVideoDisplayCompatibleSizes(a)}};_fwsdk.AdManager.prototype.constructor=_fwsdk.AdManager;
_fwsdk.Slot=function(a){this._adManager=a;this._customId="";this._scheduledAdInstance=this._currentAdInstance=this._type=null;this._adInstances=[];this._eventCallbacks=[];this._parameters={};this._onSlotEnded=function(){};this._onSlotEnded=this._last=this._init=null;this._state=_fwsdk.MediaInitState.instance};_fwsdk.Slot.prototype={};_fwsdk.Slot.prototype.constructor=_fwsdk.Slot;
_fwsdk.Util.mixin(_fwsdk.Slot.prototype,{setParameter:function(a,b){if(b)this._parameters[a]=b;else delete this._parameters[a]},getCustomId:function(){return this._customId},getType:function(){return this._type},getTimePosition:function(){return this._timePosition},getTimePositionClass:function(){return this._timePositionClass.toUpperCase()},getWidth:function(){return this._width},getHeight:function(){return this._height},getBase:function(){if(!this._baseId)return null;return document.getElementById(this._baseId)},
dispose:function(){this._onTimeUpdate&&this._contentVideo.removeEventListener("timeupdate",this._onTimeUpdate,false)},parse:function(a){this._customId=a.customId;this._timePosition=a.timePosition*1;this._timePositionClass=a.timePositionClass;this._adUnit=a.adUnit;for(var b=0,c=a.eventCallbacks||[];b<c.length;b++){var d=c[b],e=_fwsdk.EventCallback.newEventCallback(this._adManager,d.name,d.type);if(e){e._slot=this;e.parse(d);this._eventCallbacks.push(e)}}b=0;for(c=a.selectedAds||[];b<c.length;b++){d=
c[b];a=new _fwsdk.AdInstance(this._adManager);a._slot=this;a.parse(d);this._adInstances.push(a)}},copy:function(){var a=new _fwsdk.Slot;a._adManager=this._adManager;a._type=this._type;a._width=this._width;a._height=this._height;a._customId=this._customId;a._adUnit=this._adUnit;a._slotProfile=this._slotProfile;a._timePositionClass=this._timePositionClass;a._acceptPrimaryContentType=this._acceptPrimaryContentType;a._acceptContentType=this._acceptContentType;return a},schduleAdInstance:function(){return this._scheduledAdInstance=
this._currentAdInstance.schedule()},play:function(a){this._onSlotEnded=this._onSlotEnded||a;this._state.play(this)},onStartPlaying:function(){this._init="1";this._onStartPlaying()},onStartReplaying:function(){this._init="2";this._onStartPlaying()},onCompletePlaying:function(){this._onCompletePlaying()},onCompleteReplaying:function(){this._onCompletePlaying()},playNextAdInstance:function(){this._playNextAdInstance()||this._state.complete(this)},scheduleAdInstance:function(){return this._scheduledAdInstance=
this._currentAdInstance.schedule()},_onStartPlaying:function(){if(this._type==_fwsdk.SLOT_TYPE_TEMPORAL){var a=_fwsdk.EventCallback.getEventCallback(this._eventCallbacks,_fwsdk.EVENT_SLOT_IMPRESSION,_fwsdk.EVENT_TYPE_IMPRESSION);a&&a.process()}for(a=0;a<this._adInstances.length;a++)this._adInstances[a]._rendererController.reset();this.playNextAdInstance()},_onCompletePlaying:function(){var a=this._onSlotEnded;this._onSlotEnded=null;a&&a()},_playNextAdInstance:function(){if(this._state!=_fwsdk.MediaPlayingState.instance&&
this._state!=_fwsdk.MediaReplayingState.instance)return false;this._commitScheduledAdInstance();this._currentAdInstance=this._nextPlayableAdInstance();if(!this._currentAdInstance)return false;this._currentAdInstance._rendererController.play();return true},_commitScheduledAdInstance:function(){if(this._scheduledAdInstance)for(var a=0;a<this._adInstances.length;a++)if(this._adInstances[a]==this._currentAdInstance){this._adInstances.splice(a,1,this._scheduledAdInstance);this._scheduledAdInstance=null}},
_nextPlayableAdInstance:function(){for(var a=0;a<this._adInstances.length;a++)if(this._adInstances[a]._rendererController.playable())return this._adInstances[a];return null},toString:function(){return"[Slot "+this._customId+"]"}});_fwsdk.NullAdRenderer=function(){};
_fwsdk.NullAdRenderer.prototype={start:function(a){a.setCapability(_fwsdk.EVENT_AD_CLICK,_fwsdk.CAPABILITY_STATUS_OFF);a.processEvent({name:_fwsdk.RENDERER_STATE_STARTED});a.processEvent({name:_fwsdk.RENDERER_STATE_COMPLETING});a.processEvent({name:_fwsdk.RENDERER_STATE_COMPLETED})},info:function(){return{moduleType:_fwsdk.MODULE_TYPE_RENDERER}}};_fwsdk.NullAdRenderer.prototype.constructor=_fwsdk.NullAdRenderer;_fwsdk.Url=function(a){this._session=this._base="";this._parameters=new _fwsdk.Hash;this.setString(a)};
_fwsdk.Url.prototype={};_fwsdk.Url.prototype.constructor=_fwsdk.Url;
_fwsdk.Util.mixin(_fwsdk.Url.prototype,{setString:function(a){if(!(this._string==a||!a)){this._string=a;a=a.split("?");this._base=a[0];this._parameters=new _fwsdk.Hash;if(a[1]){var b=a[1].indexOf(";");if(b>0&&a[1].indexOf("session=")===0){this._session=a[1].substring(0,b+1);a=a[1].substring(b+1)}else a=a[1];a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c];b=d.indexOf("=");if(!(b<0)){var e=decodeURIComponent(d.substring(0,b));b=decodeURIComponent(d.substring(b+1));this._parameters.setKeyValue(e,
b)}}}}},setParameter:function(a,b){this._parameters.setKeyValue(a,b,0);this._string=null},getParameter:function(a){return this._parameters.getValue(a)},toString:function(){if(this._string)return this._string;this._parameters.move("cr",-1);for(var a=this._parameters._keys,b=[],c=0;c<a.length;c++){var d=a[c],e=this._parameters.getValue(d);b.push(encodeURIComponent(d)+"="+encodeURIComponent(e))}return this._string=this._base+"?"+this._session+b.join("&")}});_fwsdk.OverlayAdRenderer=function(){};
_fwsdk.OverlayAdRenderer.prototype={start:function(a){if(_fwsdk.Util.isiPad()){a.setCapability(_fwsdk.EVENT_AD_CLICK,_fwsdk.CAPABILITY_STATUS_OFF);var b=a.getAdInstance(),c=b.getSlot().getBase();b=b.getPrimaryCreativeRendition();var d=b.getPrimaryCreativeRenditionAsset(),e=document.createElement("div");c.appendChild(e);c.style.position="relative";this._layoutOverlayNode(a,e,c,b);if(_fwsdk.Util.isBlank(d.getUrl()))_fwsdk.Util.buildNode(e,d.getContent());else{var f=document.createElement("iframe");
f.frameBorder=0;f.scrolling="no";f.src=d.getUrl();f.width=this._renditionWidth;f.height=this._renditionHeight;e.appendChild(f)}setTimeout(function(){a.processEvent({name:_fwsdk.RENDERER_STATE_COMPLETING});c.removeChild(e);a.processEvent({name:_fwsdk.RENDERER_STATE_COMPLETED})},1E3*b.getDuration());a.processEvent({name:_fwsdk.RENDERER_STATE_STARTED})}else a.processEvent({name:_fwsdk.RENDERER_STATE_FAILED,info:{errorModule:"OverlayAdRenderer",errorInfo:"only support iPad"}})},info:function(){return{INFO_KEY_MODULE_TYPE:_fwsdk.MODULE_TYPE_RENDERER}},
_layoutOverlayNode:function(a,b,c,d){var e=c.style.pixelWidth?c.style.pixelWidth:c.offsetWidth;c=c.style.pixelHeight?c.style.pixelHeight:c.offsetHeight;this._renditionWidth=d.getWidth();if(this._renditionWidth<=0||this._renditionWidth>e)this._renditionWidth=e;this._renditionHeight=d.getHeight();if(this._renditionHeight<=0)this._renditionHeight=0.25*c;else if(this._renditionHeight>c)this._renditionHeight=c;b.style.width=this._renditionWidth;b.style.height=this._renditionHeight;b.style.position="absolute";
b.style.overflow="hidden";a=a.getParameter("renderer.overlay.primaryAnchor")||"bc";if(a=="tl")b.style.left=b.style.top=0;else if(a=="tr")b.style.right=b.style.top=0;else if(a=="bl")b.style.left=b.style.bottom=0;else if(a=="br")b.style.right=b.style.bottom=0;else if(a=="tc"){b.style.left=(e-this._renditionWidth)*0.5;b.style.top=0}else if(a=="lm"){b.style.top=(c-this._renditionHeight)*0.5;b.style.left=0}else if(a=="rm"){b.style.top=(c-this._renditionHeight)*0.5;b.style.right=0}else{b.style.left=(e-
this._renditionWidth)*0.5;b.style.bottom=0}}};_fwsdk.OverlayAdRenderer.prototype.constructor=_fwsdk.OverlayAdRenderer;_fwsdk.version="js-3.5.2-r5798-201011160940";if(typeof window!="undefined"){if(!window._fw_admanager)window._fw_admanager={};window._fw_admanager.version=_fwsdk.version}_fwsdk.log=function(){if(window.console&&window.console.log){for(var a="[FW]",b=0;b<arguments.length;b++)a+=" "+arguments[b];window.console.log(a)}};_fwsdk.log("FreeWheel Integration Runtime",_fwsdk.version);
_fwsdk._firstAdTimeout=false;_fwsdk._instanceCounter=0;_fwsdk._instanceQueue={};_fwsdk.CAPABILITY_CHECK_COMPANION="checkCompanion";_fwsdk.CAPABILITY_CHECK_TARGETING="checkTargeting";_fwsdk.CAPABILITY_SLOT_TEMPLATE="supportsSlotTemplate";_fwsdk.CAPABILITY_ADUNIT_IN_MULTIPLE_SLOTS="supportsAdUnitInMultipleSlots";_fwsdk.CAPABILITY_REQUIRES_VIDEO_CALLBACK_URL="requiresVideoCallbackUrl";_fwsdk.CAPABILITY_SKIP_AD_SELECTION="skipsAdSelection";_fwsdk.CAPABILITY_SLOT_CALLBACK="supportsSlotCallback";
_fwsdk.CAPABILITY_EXPECT_MULTIPLE_CREATIVE_RENDITIONS="expectMultipleCreativeRenditions";_fwsdk.CAPABILITY_RECORD_VIDEO_VIEW="recordVideoView";_fwsdk.CAPABILITY_SUPPORT_NULL_CREATIVE="supportNullCreative";_fwsdk.SLOT_TYPE_TEMPORAL="temporal";_fwsdk.SLOT_TYPE_VIDEOPLAYER_NONTEMPORAL="videoPlayerNonTemporal";_fwsdk.SLOT_TYPE_SITESECTION_NONTEMPORAL="siteSectionNonTemporal";_fwsdk.TIME_POSITION_CLASS_PREROLL="PREROLL";_fwsdk.TIME_POSITION_CLASS_MIDROLL="MIDROLL";_fwsdk.TIME_POSITION_CLASS_POSTROLL="POSTROLL";
_fwsdk.TIME_POSITION_CLASS_OVERLAY="OVERLAY";_fwsdk.EVENT_SLOT_END="onSlotEnd";_fwsdk.EVENT_REQUEST_COMPLETE="onRequestComplete";_fwsdk.CAPABILITY_STATUS_OFF=0;_fwsdk.CAPABILITY_STATUS_ON=1;_fwsdk.PARAMETER_LEVEL_GLOBAL=0;_fwsdk.PARAMETER_LEVEL_OVERRIDE=4;_fwsdk.PARAMETER_PLAY_MIDROLL_BY_CURRENT_VIDEO_ELEMENT=false;

}
/*
     FILE ARCHIVED ON 18:26:18 Nov 30, 2010 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 17:24:06 Jul 27, 2024.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 0.639
  exclusion.robots: 0.028
  exclusion.robots.policy: 0.011
  esindex: 0.013
  cdx.remote: 29.37
  LoadShardBlock: 241.92 (3)
  PetaboxLoader3.datanode: 110.853 (4)
  PetaboxLoader3.resolve: 262.371 (2)
  load_resource: 213.122
*/